version: '3'

tasks:
  build-http:
    dir: cmd/http
    cmds:
      - go build -o ../../http_service ./...
  run-http:
    cmds:
      - task: build-http
      - ./http_service
      - defer: rm ./http_service
  build-consumer:
    dir: cmd/consumer
    cmds:
      - go build -o ../../consumer_service ./...
  run-consumer:
    cmds:
      - task: build-consumer
      - ./consumer_service
      - defer: rm ./consumer_service