version: '3'

tasks:
  build-http:
    dir: cmd/http
    cmds:
      - go build -o ../../http_service ./...
  run-http:
    env:
      APP_NAME: "http-adios"
    cmds:
      - task: build-http
      - ./http_service
      - defer: rm ./http_service
  build-consumer:
    dir: cmd/consumer
    cmds:
      - go build -o ../../consumer_service ./...
  run-consumer:
    env:
      APP_NAME: "consumer-adios"
    cmds:
      - task: build-consumer
      - ./consumer_service
      - defer: rm ./consumer_service
  build-grpc:
    dir: cmd/grpc
    cmds:
      - go build -o ../../grpc_service ./...
  run-grpc:
    env:
      APP_NAME: "grpc-adios"
    cmds:
      - task: build-grpc
      - ./grpc_service
      - defer: rm ./grpc_service
  proto-gen:
    cmds:
      - rm -rf gen/proto_go
      - buf generate